import = [
  "~/.dotfiles/config/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 0


# opacity = 10
blur = true


[font.bold]
family = "Cascadi Mono"
style = "Bold"


[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Cascadia Mono"
style = "Italic"

[font.normal]
family = "Cascadia Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[font]
size = 14

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "CopySelection"
mouse = "Right"

[colors]
draw_bold_text_with_bright_colors = true
